#!/bin/bash
# The command to build the Angular project so that it can be served by Github pages.
# The angular.json file should have the outputPath set to docs:
# "outputPath": "docs",
# The Github setting for pages should choose the docs folder.
ng build --base-href "https://davidgma.github.io/codelabs-sheetsapi-angular/docs" 
